site:
  title: Stackable Documentation
  url: https://stackackable.svenpetersen.net
  #url: http://localhost:5000
  start_page: home::index.adoc
  robots: allow

content:
  sources: 
  - url: https://github.com/stackabletech/agent.git
    branches: main
    start_path: docs
  - url: https://github.com/stackabletech/documentation.git
    branches: main
  - url: https://github.com/stackabletech/kafka-operator.git
    branches: main
    start_path: docs
  - url: https://github.com/stackabletech/monitoring-operator.git
    branches: main
    start_path: docs
  - url: https://github.com/stackabletech/nifi-operator.git
    branches: main
    start_path: docs
  - url: https://github.com/stackabletech/opa-operator.git
    branches: main
    start_path: docs
  - url: https://github.com/stackabletech/regorule-operator.git
    branches: main
    start_path: docs
  - url: https://github.com/stackabletech/spark-operator.git
    branches: main
    start_path: docs
  - url: https://github.com/stackabletech/zookeeper-operator.git
    branches: main
    start_path: docs

ui:
  bundle:
    url: ../stackable-documentation-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
#   - path: ui.yml
#     contents: |
#       static_files: [ .nojekyll ]
#   - path: .nojekyll

asciidoc:
  attributes:
    base-repo: https://github.com/stackabletech
